name: Build and publish Oracle Database container image to GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'OracleDatabase/SingleInstance/dockerfiles/*'
      - '.github/workflows/build-and-push-oracle-database-image.yml'
  workflow_dispatch:

env:
  IMAGE_NAME: oracle-db
  TAG: xe

jobs:
  push:
    name: Build and push Oracle Database image

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${GITHUB_ACTOR,,} --password-stdin

      - name: Repository owner needs to be lowercase
        id: repo-owner
        run: |
          REPO_OWNER=${{ github.repository_owner }}
          echo "::set-output name=repo-owner::${REPO_OWNER,,}"

      - name: Build Oracle Database image
        run: |
          cd OracleDatabase/SingleInstance/dockerfiles
          ./buildContainerImage.sh -v 21.3.0 -x -t ${{ steps.repo-owner.outputs.repo-owner }}/oracledb:21.3-xe

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io:${{ steps.repo-owner.outputs.repo-owner }}/oracledb:21.3-xe
